### ISSUE TITLE
Support docker image name configuration

### ISSUE THREAD

**Issue by pgorbachev** [octopusden/octopus-components-registry-service#42]
1) Support configuration of docker image name for component in the following section 
```groovy
  docker {
      imageName = 'some image name'
  }
```
2) It should be supported  in 
a)
```groovy
Defaults {
}
```
b) 
 component-level
c)
version range

3) following expressions have to be also supported:

- $namespaceFromGroupId for function that transform groupId = 'org.company.lev3.lev4' to docker namespace 'lev3/lev4'
- $componentKey 

For example,  for configuration 
```groovy
"my-service" {
    groupId = "org.octopusden.octopus.system-test"
    docker {
        imageName = '$namespaceFromGroupId/$componentKey'
    }
}
```
Alternatively:

```groovy
"my-service" {
    groupId = "org.octopusden.octopus.system-test"
    distribution {
        DOCKER = '$namespaceFromGroupId/$componentKey'
    }
}
```

dockerImageName will be 'octopus/system-test/my-service`

4. dockerImageName should be added to Component model

https://github.com/octopusden/octopus-components-registry-service/blob/main/components-registry-service-core/src/main/kotlin/org/octopusden/octopus/components/registry/core/dto/Component.kt

**Comment by fishinitself** [comment]
@pgorbachev stupid question - if an imageName is just a function of the component ID and the component GAV , why do we need to declare it separately?

**Comment by pgorbachev** [comment]
> @pgorbachev stupid question - if an imageName is just a function of the component ID and the component GAV , why do we need to declare it separately?

Different rules including static name of the image have to be supported

**Comment by aryabokon** [comment]
Давайте сделаем версионируемым поле

**Comment by pgorbachev** [comment]
Implemented in another way
