### ISSUE TITLE
Support specification of docker image for distribution

### ISSUE THREAD

**Issue by pgorbachev** [octopusden/octopus-components-registry-service#45]
Support

```
distribution {
    DOCKER="test/test-component"
}
```
Also should be supported in end-point
```
rest/api/2/components/{component}/versions/1.2.3/distribution
```

**Comment by pgorbachev** [comment]
@aryabokon , @CamaradeRoman , please look are you ok with with configuration in CRS?

**Comment by aryabokon** [comment]
DOCKER in distribution section looks good, but I will appreciate anyone who add this parameter to distribution section of  `rest/api/2/components/{component}/versions/1.2.3`

**Comment by CamaradeRoman** [comment]
@pgorbachev it is OK if we fix the agreement that image tag must be equal to version. But it means that we won't be able to use "standard" approach of image classification like `postgres:13.12`, `postgres:13.12-alpine`, `postgres:13.12-alpine3.17`, `postgres:13.12-alpine3.18`, `postgres:13.12-bookworm` etc.

**Comment by pgorbachev** [comment]
Already implemented
